name: 'Pages Jekyll'
description: 'A simple GitHub Action for producing Jekyll build artifacts compatible with GitHub Pages'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    # `id -u $(whoami)` in an action outputs this value and allows the workdir
    # to be writable
    JEKYLL_UID: "1001"
